name: demo-ci-cd

on:
  push:
    branches:
      - 'staging'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
       name: Checkout 
       uses: actions/checkout@v3
      -
       name : Main
       run: | 
         ls
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cicd-repos:latest
      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
      - 
        name: deploy
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      -
        name : Main
        run: |
          ls
          kubectl get ns
          kubectl aplly -f 
