name: demo-ci-cd


on:
  push:
    branches:
      - 'staging'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
       name: Checkout 
       uses: actions/checkout@v3
      -
       name : Main
       run: | 
         ls
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cicd-repos:latest-${{ github.run_number }}
      - 
        name: Configure to kubernetes
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      -
        name : Deploy
        run: |
          cd manifest
          ls
          kubectl get ns
          #kubectl apply -f deployment.yaml -n name_space
          #kubectl apply -f service.yaml -n name_space
          #kubectl get pod -n name_space
          
          #Using Helm-Chart
          #helm upgrade sample --install sample/ -f values.yaml -n $name_space --create-namespace --set image.tag=latest-${{ github.run_number }}
